# This is a YAML file defining a serverless microservice for sending notifications

# The name of the service
service: microservice-notifications

# Specify how variables should be resolved
variablesResolutionMode: null

# Configuration for the AWS provider
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  # Set the stage based on command line option or default to "dev"
  stage: ${opt:stage,'dev'}
  # Set the AWS region based on command line option or default to "us-east-2"
  region: ${opt:region,'us-east-2'}
  tags:
    Project: microservice-notifications-service
    # Set the environment tag based on stage
    Environment: ${opt:stage,'dev'}
  deploymentPrefix: microservice-notifications-serverless
  # Configuration for the HTTP API
  httpApi:
    cors: true
    disableDefaultEndpoint: false
    metrics: true
    useProviderTags: true
  environment:
    NODE_ENV: dev

# Plugins to use with the serverless framework
plugins:
  - serverless-plugin-typescript 
  - serverless-offline
  - serverless-dotenv-plugin

# Package options
package:
  individually: true
  # Only include this file for dev environment
  include:
    - config/.env.dev

# Functions to deploy
functions:
  receipt:
    handler: app/handler.receipt
    events:
      # HTTP endpoint to receive receipts
      - http:
          path: receipt
          method: post
      # SQS queues to send notifications
      - sqs:
          arn:aws:sqs:us-east-2:482041903125:notification-mail
      - sqs:
          arn:aws:sqs:us-east-2:482041903125:notification-sms
      - sqs:
          arn:aws:sqs:us-east-2:482041903125:notification-whatsapp
      - sqs:
          arn:aws:sqs:us-east-2:482041903125:notification-push
  sendmail:
    handler: app/handler.sendmail
    events:
      # HTTP endpoint to send emails
      - http:
          path: sendmail
          method: post
  sendwhatsapp:
    handler: app/handler.sendwhatsapp
    events:
      # HTTP endpoint to send WhatsApp messages
      - http:
          path: sendwhatsapp
          method: post
  sendsms:
    handler: app/handler.sendsms
    events:
      # HTTP endpoint to send SMS messages
      - http:
          path: sendsms
          method: post
  schedul:
    handler: app/handler.schedul
    events:
      # HTTP endpoint to schedule notifications
      - http:
          path: schedul
          method: post
        # CRON to schedule the execution of the function
#      - schedule: cron(*/5 * 16-17 2 ? *)
  
# Custom options
custom:
  # Configuration for the serverless-offline plugin
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
  # Configuration for the dotenv plugin
  dotenv:
    path: config/.env.${self:provider.stage}